name: Auto Promote Pkgs

on:
  schedule:
    - cron: "0 10 * * MON-FRI"  # Weekdays at 10 AM UTC
  workflow_dispatch:

jobs:
  auto-promote:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout Munki
        uses: actions/checkout@v4
        with:
          repository: 'munki/munki'
          ref: '6b4ad647c4b863709a4cff85596684d3620b426f'  # last commit with Python makecatalogs
          path: munki

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run makecatalogs
        run: uv run python munki/code/client/makecatalogs -s -f munki_repo

      - name: Run auto promotion
        run: |
          git config --global user.name "Auto Promoter"
          uv run bin/auto_promotion.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
